import{initializeApp}from'https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js';
import{getFirestore,collection,onSnapshot,addDoc,updateDoc,deleteDoc,doc,getDoc,setDoc,getDocs,serverTimestamp}from'https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js';
import{getStorage,ref as sref,uploadBytes,getDownloadURL,deleteObject}from'https://www.gstatic.com/firebasejs/11.6.1/firebase-storage.js';
const cfg={apiKey:'AIzaSyCgE9Xj3RWmoDs0gaCbwJbKZ6N7HjFw4tA',authDomain:'vectech-2114d.firebaseapp.com',projectId:'vectech-2114d',storageBucket:'vectech-2114d.firebasestorage.app',messagingSenderId:'1099462295117',appId:'1:1099462295117:web:ce5a0a6ef0749d1f8f2604'},APP='product-issue-tracker-01',MAX_MEDIA=12,MAX_IMG=1800,MAX_VIDEO=200*1024*1024,PW_ITER=120000;
const app=initializeApp(cfg,'vectech-issue-app-v13'),db=getFirestore(app),storage=getStorage(app),BASE=['artifacts',APP,'public','data'];
const issuesCol=collection(db,...BASE,'issues'),settingsRef=doc(db,...BASE,'config','settings');
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],addMedia=[],editMedia=[],keepMedia=[],editingId=null,pendingAction=null,unlockedUntil=0,pwExists=false;
const today=()=>new Date().toLocaleDateString('en-CA');
function toast(msg,bad=false){const x=document.createElement('div');x.className=`toast ${bad?'bad':''}`;x.textContent=msg;$('toast').appendChild(x);setTimeout(()=>x.remove(),5000)}
function fail(label,e){console.error(label,e);toast(`${label}：${e?.code||'error'} ${e?.message||e}`,true);$('conn').textContent=`${label}：${e?.code||'error'}`;$('conn').className='badtxt'}
function isVideo(m){return m?.type==='video'||String(m?.mime||'').startsWith('video/')||/\.(mp4|mov|m4v|webm|avi|mkv)$/i.test(m?.name||m?.path||'')}
function mediaList(r){const a=Array.isArray(r?.photos)?r.photos:Array.isArray(r?.media)?r.media:[];return a.map(m=>({...m,type:m.type||(String(m.mime||'').startsWith('video/')?'video':'image')}))}
function mediaThumb(m,removeFn=''){const inner=isVideo(m)?`<video src="${esc(m.url)}" controls preload="metadata"></video>`:`<img src="${esc(m.url)}" loading="lazy">`;return`<div class="media"><div class="mediaInner">${inner}</div>${removeFn?`<button class="x" type="button" onclick="${removeFn}">×</button>`:''}<div class="mediaName">${isVideo(m)?'🎬 ':''}${esc(m.name||'附件')}</div></div>`}
function mediaGrid(list,removePrefix){return list.map((m,i)=>mediaThumb(m,removePrefix?`${removePrefix}(${i})`:'')).join('')}
function render(){const q=$('search').value.trim().toLowerCase(),fs=$('fs').value,fc=$('fc').value,arr=rows.filter(r=>(!q||[r.id,r.product,r.category,r.assignee,r.description,r.action,r.remarks].join(' ').toLowerCase().includes(q))&&(!fs||r.status===fs)&&(!fc||r.category===fc));$('count').textContent=`${arr.length}/${rows.length} 筆`;$('table').innerHTML=arr.map(r=>{const ms=mediaList(r);return`<tr><td>${esc(r.id)}</td><td>${esc(r.date)}</td><td>${esc(r.product)}</td><td>${esc(r.category)}</td><td><div class="desc">${esc(r.description)}</div><button class="miniLink" onclick="quickDescription('${r._id}')">✎ 修改議題說明（免密碼）</button></td><td>${esc(r.assignee)}</td><td>${ms.length?`<div class="tinyMedia">${ms.slice(0,3).map(m=>isVideo(m)?'<span>🎬</span>':`<img src="${esc(m.url)}">`).join('')}${ms.length>3?`<b>+${ms.length-3}</b>`:''}</div>`:'—'}</td><td>${esc(r.action)}</td><td>${esc(r.target||'')}</td><td>${esc(r.status)}</td><td><button class="miniLink" onclick="fullEdit('${r._id}')">🔒 完整編輯</button></td></tr>`}).join('');$('cards').innerHTML=arr.map(r=>{const ms=mediaList(r);return`<article class="issue"><div class="row"><div><h3>#${esc(r.id)} ${esc(r.product)}</h3><div class="muted">${esc(r.date)}・${esc(r.category)}・${esc(r.assignee)}</div></div><span class="status">${esc(r.status)}</span></div><div class="desc"><b>議題：</b>${esc(r.description)}</div><button class="miniLink" onclick="quickDescription('${r._id}')">✎ 修改議題說明（免密碼）</button><div class="desc"><b>處理進度：</b>${esc(r.action)||'—'}</div><div class="desc"><b>預計完成：</b>${esc(r.target)||'—'}</div>${ms.length?`<div class="mediaGrid">${ms.map(m=>`<a href="${esc(m.url)}" target="_blank">${mediaThumb(m)}</a>`).join('')}</div>`:''}<div class="actions"><button class="miniLink" onclick="fullEdit('${r._id}')">🔒 完整編輯</button><button class="miniLink dangerLink" onclick="removeIssue('${r._id}')">刪除</button></div></article>`}).join('')}
function subscribe(){onSnapshot(issuesCol,s=>{rows=s.docs.map(d=>({_id:d.id,...d.data()})).sort((a,b)=>(+a.id||0)-(+b.id||0));render();$('conn').textContent='● 雲端已同步';$('conn').className='oktxt'},e=>fail('讀取資料失敗',e))}
async function loadPassword(){try{pwExists=!!(await getDoc(settingsRef)).data()?.passwordHash}catch(e){fail('讀取密碼設定失敗',e)}}
function salt(){const a=new Uint8Array(16);crypto.getRandomValues(a);return[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hashPw(p,s,it=PW_ITER){const enc=new TextEncoder(),k=await crypto.subtle.importKey('raw',enc.encode(p),{name:'PBKDF2'},false,['deriveBits']),b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(s),iterations:it,hash:'SHA-256'},k,256);return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function savePw(p){const s=salt(),h=await hashPw(p,s);await setDoc(settingsRef,{passwordSalt:s,passwordHash:h,passwordIterations:PW_ITER,updatedAt:serverTimestamp()},{merge:true});pwExists=true;unlockedUntil=Date.now()+1800000}
async function verifyPw(p){const d=(await getDoc(settingsRef)).data()||{};return!!d.passwordHash&&!!d.passwordSalt&&(await hashPw(p,d.passwordSalt,d.passwordIterations||PW_ITER))===d.passwordHash}
function unlocked(){return Date.now()<unlockedUntil}
function closePw(){$('pwModal').classList.remove('on')}
function openPw(){const box=$('pwBox');$('pwModal').classList.add('on');box.innerHTML=pwExists?`<input id="pw" type="password" placeholder="輸入編輯密碼"><button id="pwOk" class="primary">確認密碼</button>`:`<input id="pw1" type="password" placeholder="設定編輯密碼（至少4碼）"><input id="pw2" type="password" placeholder="再次輸入新密碼"><button id="pwSetup" class="primary">設定密碼</button>`;if(pwExists){$('pwOk').onclick=async()=>{try{if(await verifyPw($('pw').value)){unlockedUntil=Date.now()+1800000;const p=pendingAction;pendingAction=null;closePw();toast('密碼正確，已解鎖30分鐘');if(p==='changePw')changePw();else if(p?.startsWith('DELETE:'))await doDelete(p.slice(7));else if(p)openFullEdit(p)}else toast('密碼錯誤',true)}catch(e){fail('密碼驗證失敗',e)}}}else{$('pwSetup').onclick=async()=>{const a=$('pw1').value,b=$('pw2').value;if(a.length<4||a!==b)return toast('請確認密碼至少4碼且兩次一致',true);try{await savePw(a);closePw();toast('編輯密碼已設定')}catch(e){fail('設定密碼失敗',e)}}}}
function changePw(){$('pwText').textContent='目前密碼已驗證，設定新的編輯密碼';const box=$('pwBox');$('pwModal').classList.add('on');box.innerHTML='<input id="np1" type="password" placeholder="新密碼（至少4碼）"><input id="np2" type="password" placeholder="再次輸入新密碼"><button id="npOk" class="primary">更改密碼</button>';$('npOk').onclick=async()=>{const a=$('np1').value,b=$('np2').value;if(a.length<4||a!==b)return toast('請確認新密碼至少4碼且一致',true);try{await savePw(a);closePw();toast('編輯密碼已更新')}catch(e){fail('更改密碼失敗',e)}}}
async function prepImage(f){if(!f.type.startsWith('image/'))return f;return new Promise((res,rej)=>{const im=new Image(),u=URL.createObjectURL(f);im.onload=()=>{const sc=Math.min(1,MAX_IMG/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*sc));c.height=Math.max(1,Math.round(im.height*sc));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);b?res(new File([b],f.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'})):rej(new Error('圖片壓縮失敗'))},'image/jpeg',.82)};im.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('無法讀取圖片：'+f.name))};im.src=u})}
async function uploadMedia(issueId,files){const out=[];for(let i=0;i<files.length;i++){const f=files[i];if(f.type.startsWith('video/')&&f.size>MAX_VIDEO)throw new Error(`${f.name} 超過200MB`);toast(`${f.type.startsWith('video/')?'影片':'照片'}上傳中 ${i+1}/${files.length}`);const actual=await prepImage(f),ext=actual.type.startsWith('video/')?(actual.name.split('.').pop()||'mp4'):'jpg',name=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2))+'.'+ext,p=`${APP}/issues/${issueId}/${name}`,r=sref(storage,p);await uploadBytes(r,actual,{contentType:actual.type});out.push({name:f.name,path:p,url:await getDownloadURL(r),type:actual.type.startsWith('video/')?'video':'image',mime:actual.type})}return out}
async function delMedia(list){for(const m of list||[]){if(!m.path)continue;try{await deleteObject(sref(storage,m.path))}catch(e){console.warn('delete media skipped',m.path,e)}}}
function addPreview(){ $('preview').innerHTML=addMedia.map((f,i)=>mediaThumb({name:f.name,url:URL.createObjectURL(f),type:f.type.startsWith('video/')?'video':'image'},`removeAdd(${i})`)).join('') }
window.removeAdd=i=>{addMedia.splice(i,1);addPreview()};
function editPreview(){ $('epreview').innerHTML=editMedia.map((f,i)=>mediaThumb({name:f.name,url:URL.createObjectURL(f),type:f.type.startsWith('video/')?'video':'image'},`removeEdit(${i})`)).join('') }
window.removeEdit=i=>{editMedia.splice(i,1);editPreview()};
function keepPreview(){ $('existing').innerHTML=keepMedia.length?mediaGrid(keepMedia,'removeKeep'):'<span class="muted">目前沒有附件</span>' }
window.removeKeep=i=>{keepMedia.splice(i,1);keepPreview()};
window.quickDescription=id=>{const r=rows.find(x=>x._id===id);if(!r)return;$('descText').value=r.description||'';$('descModal').classList.add('on');$('saveDesc').onclick=async()=>{try{await updateDoc(doc(db,...BASE,'issues',id),{description:$('descText').value.trim(),updatedAt:serverTimestamp()});$('descModal').classList.remove('on');toast('議題說明已更新')}catch(e){fail('修改說明失敗',e)}}}
window.fullEdit=id=>{if(!unlocked()){pendingAction=id;return openPw()}openFullEdit(id)};
function openFullEdit(id){const r=rows.find(x=>x._id===id);if(!r)return;editingId=id;$('eid').value=r.id||'';$('edate').value=r.date||'';$('eproduct').value=r.product||'';$('ecategory').value=r.category||'其他';$('eassignee').value=r.assignee||'';$('edescription').value=r.description||'';$('eaction').value=r.action||'';$('etarget').value=r.target||'';$('estatus').value=r.status||'待處理';$('eremarks').value=r.remarks||'';keepMedia=mediaList(r);editMedia=[];keepPreview();editPreview();$('editModal').classList.add('on')}
window.removeIssue=id=>{if(!unlocked()){pendingAction='DELETE:'+id;return openPw()}doDelete(id)};
async function doDelete(id){if(!confirm('確定要刪除這筆議題及其所有照片／影片嗎？'))return;try{const r=rows.find(x=>x._id===id);await deleteDoc(doc(db,...BASE,'issues',id));await delMedia(mediaList(r));toast('刪除成功')}catch(e){fail('刪除失敗',e)}}
$('media').onchange=e=>{const fs=[...e.target.files];if(addMedia.length+fs.length>MAX_MEDIA)return toast(`每筆最多 ${MAX_MEDIA} 個照片／影片`,true);addMedia=[...addMedia,...fs];addPreview();e.target.value=''};
$('emedia').onchange=e=>{const fs=[...e.target.files];if(keepMedia.length+editMedia.length+fs.length>MAX_MEDIA)return toast(`每筆最多 ${MAX_MEDIA} 個照片／影片`,true);editMedia=[...editMedia,...fs];editPreview();e.target.value=''};
$('addForm').onsubmit=async e=>{e.preventDefault();const b=$('addBtn');b.disabled=true;b.textContent=addMedia.length?'新增＋上傳附件…':'寫入雲端中…';try{const no=String(rows.reduce((m,r)=>Math.max(m,+r.id||0),0)+1),d=await addDoc(issuesCol,{id:no,date:$('date').value,product:$('product').value.trim(),category:$('category').value,assignee:$('assignee').value.trim(),description:$('description').value.trim(),action:$('action').value.trim(),target:$('target').value,status:$('status').value,remarks:$('remarks').value.trim(),photos:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(addMedia.length){const up=await uploadMedia(d.id,addMedia);await updateDoc(doc(db,...BASE,'issues',d.id),{photos:up,updatedAt:serverTimestamp()})}e.target.reset();$('date').value=today();addMedia=[];addPreview();toast('新增成功，資料與附件已寫入雲端')}catch(e){fail('新增失敗',e)}finally{b.disabled=false;b.textContent='＋ 確定新增'}};
$('editForm').onsubmit=async e=>{e.preventDefault();if(!unlocked())return openPw();const old=rows.find(x=>x._id===editingId)||{},removed=(mediaList(old)).filter(m=>!keepMedia.some(k=>k.path===m.path));const b=e.submitter;b.disabled=true;b.textContent='儲存中…';try{const added=editMedia.length?await uploadMedia(editingId,editMedia):[];const all=[...keepMedia,...added];await updateDoc(doc(db,...BASE,'issues',editingId),{id:$('eid').value.trim(),date:$('edate').value,product:$('eproduct').value.trim(),category:$('ecategory').value,assignee:$('eassignee').value.trim(),description:$('edescription').value.trim(),action:$('eaction').value.trim(),target:$('etarget').value,status:$('estatus').value,remarks:$('eremarks').value.trim(),photos:all,updatedAt:serverTimestamp()});if(removed.length)await delMedia(removed);$('editModal').classList.remove('on');toast('完整編輯儲存成功')}catch(e){fail('更新失敗',e)}finally{b.disabled=false;b.textContent='儲存修改'}};
$('deleteEdit').onclick=async()=>{if(!editingId)return;if(!unlocked()){pendingAction='DELETE:'+editingId;return openPw()}await doDelete(editingId);$('editModal').classList.remove('on')};
$('cancelEdit').onclick=$('closeEdit').onclick=()=>{$('editModal').classList.remove('on')};$('closeDesc').onclick=()=>{$('descModal').classList.remove('on')};$('closePw').onclick=closePw;
$('pwBtn').onclick=()=>{if(!pwExists)return openPw();if(unlocked())return changePw();openPw()};$('sync').onclick=()=>location.reload();$('search').oninput=render;$('fs').onchange=render;$('fc').onchange=render;$('date').value=today();
$('export').onclick=async()=>{try{toast('正在準備 Excel…');if(!window.ExcelJS){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';s.onload=res;s.onerror=()=>rej(new Error('無法載入 ExcelJS'));document.head.appendChild(s)})}const snap=await getDocs(issuesCol),data=snap.docs.map(d=>({_id:d.id,...d.data()})).sort((a,b)=>(+a.id||0)-(+b.id||0)),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('產品討論議題');const headers=['序號','提出日期','專案／產品名稱','議題類別','議題說明','負責人員','處理對策與進度','預計完成日期','狀態','備註',...Array.from({length:MAX_MEDIA},(_,i)=>'附件'+(i+1))];ws.addRow(headers);[8,13,22,10,34,12,34,14,10,26,...Array(MAX_MEDIA).fill(15)].forEach((w,i)=>ws.getColumn(i+1).width=w);let count=0;for(const r of data){const ms=mediaList(r),row=ws.addRow([r.id||'',r.date||'',r.product||'',r.category||'',r.description||'',r.assignee||'',r.action||'',r.target||'',r.status||'',r.remarks||'',...Array(MAX_MEDIA).fill('')]);row.height=100;for(let i=0;i<ms.slice(0,MAX_MEDIA).length;i++){const m=ms[i];if(isVideo(m)){row.getCell(11+i).value={text:'🎬 影片',hyperlink:m.url};continue}try{const resp=await fetch(m.url,{cache:'no-store'});if(!resp.ok)throw new Error('HTTP '+resp.status);const buf=await resp.arrayBuffer(),a=new Uint8Array(buf);let bin='';for(let j=0;j<a.length;j+=32768)bin+=String.fromCharCode(...a.subarray(j,j+32768));const iid=wb.addImage({base64:`data:${resp.headers.get('content-type')||'image/jpeg'};base64,${btoa(bin)}`,extension:(resp.headers.get('content-type')||'image/jpeg').includes('png')?'png':'jpeg'});ws.addImage(iid,{tl:{col:10+i+.08,row:row.number-1+.08},ext:{width:96,height:80},editAs:'oneCell'});row.getCell(11+i).value={text:'照片'+(i+1),hyperlink:m.url};count++}catch(e){row.getCell(11+i).value={text:'照片連結',hyperlink:m.url}}}row.eachCell(c=>c.alignment={vertical:'top',wrapText:true})}const out=await wb.xlsx.writeBuffer(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));a.download='產品討論議題履歷表_含照片影片.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`Excel 匯出完成：${data.length} 筆、嵌入照片 ${count} 張`)}catch(e){fail('Excel 匯出失敗',e)}};
$('import').onclick=()=>$('xlsx').click();$('xlsx').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{const XLSX=window.XLSX;const wb=XLSX.read(new Uint8Array(rd.result),{type:'array',cellDates:true}),rs=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]),batch=[];for(const x of rs)batch.push(addDoc(issuesCol,{id:String(x['序號']??''),date:String(x['提出日期']??''),product:String(x['專案／產品名稱']??''),category:String(x['議題類別']||'其他'),assignee:String(x['負責人員']??''),description:String(x['議題說明']??''),action:String(x['處理對策與進度']??''),target:String(x['預計完成日期']??''),status:String(x['狀態']||'待處理'),remarks:String(x['備註']??''),photos:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await Promise.all(batch);toast(`Excel 匯入完成：${rs.length} 筆`)}catch(e){fail('匯入失敗',e)}finally{$('xlsx').value=''}};rd.readAsArrayBuffer(f)};
$('pwText').textContent='完整編輯與刪除需要密碼；議題說明可單獨免密碼修改。';
try{subscribe();loadPassword()}catch(e){fail('Firebase 初始化失敗',e)}
